baseURL = "https://cascadiarconf.org/"
title = "CascadiaRConf"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Agenda"
    identifier = "agenda"
    url = "/coming_soon/agenda/"
    weight = 3

[[menu.main]]
   name = "Current"
   parent = "agenda"
   url  = "/coming_soon/agenda/"
   weight = 3.1
    
[[menu.main]]
   name = "Past"
   parent = "agenda"
   url  = "/years"
   weight = 3.2

[[menu.main]]
    name = "Venue"
    url = "/coming_soon/venue/"
    weight = 4

[[menu.main]]
    name = "Policies"
    identifier = "policies"
    url = "/policies/"
    weight = 5

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url = "/faq/"
    weight = 6

[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 7

[[menu.main]]
    weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/pdxrconf/pdxrconf.github.io"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/cascadiarconf"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:cascadiarcon@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    social = true
    viewMorePostLink = "/blog/"
    author = "CascadiaRConf"
    defaultKeywords = ["r", "data science", "conference"]
    defaultDescription = "Cascadia R Conference is an R conference serving the Pacific Northwest region (Alaska/British Columbia/Washington/Oregon/California)."

    # Google Maps API key (if not set will default to not passing a key.)
    # #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    about_us = "<p>Cascadia R Conference is a regional R conference for the Pacific Northwest</p>"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo/logo_2023/logo_2023_small.png"
    logo_small = "img/logo/logo_2023/logo_2023_small.png"
    logo_sticker = "img/logo/logo_2023/logo_2023.png"
	  description = "CascadiaRConf is a regional R conference for the Pacific Northwest - For 2023, the conference will be held in-person and virtually!"
    #latitude = "-12.043333"
    #longitude = "-77.028333"
    
    default_sharing_image = "img/logo/logo_2023/logo_2023_small.png"
    twitterImage = "img/logo_2023_small.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'. 
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fas fa-lightbulb"
    title = "KEYNOTES"
    subtitle = "We are proud to announce this year's Keynote Speakers!"

[params.clients]
    enable = false 
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "2023 Sponsors"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Featured Speakers"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

[markup.goldmark.renderer]
  unsafe = true
